name: myapp
description: CV Dominik Ocsofszki


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/page-1/images/vector-1.png
    - assets/page-1/images/auto-group-fpil.png
    - assets/page-1/images/auto-group-y2ac.png
    - assets/page-1/images/auto-group-l9ui.png
    - assets/page-1/images/vector-2.png
    - assets/page-1/images/auto-group-ugme.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
